import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import { diceRoll, useDestiny, usePotatoes, useOrcs, txt, eventPlace, eventDescription, eventEffect } from '../game/game-logic'

export function GameInterface(props: { destiny: number, potatoes: number, orcs: number }) {
  return (
    <div className='border-2 border-black'>
      <div className="flex gap-5 flex-col mr-auto ml-36">
        <div className="destiny flex flex-row gap-5">
          <div className="mr-3">Destiny</div>
          <div>{props.destiny}</div>
        </div>
        <div className="potatoes flex flex-row gap-5">
          <div className="">Potatoes</div>
          <div>{props.potatoes}</div>
        </div>
        <div className="orcs flex flex-row gap-5">
          <div className="mr-8">Orcs</div>
          <div>{props.orcs}</div>
        </div>
      </div>
    </div>
  )
}

const Home: NextPage = () => {

  const { destiny, desChange } = useDestiny()
  const { potatoes, potChange } = usePotatoes()
  const { orcs, orcChange } = useOrcs()

  const [text, setText] = useState(txt)

  function textChange() {
    setText(txt)
  }

  let [showEvent, setShowEvent] = useState(false)

  function showEventWindow() {
    setShowEvent(!showEvent)
    console.log(showEvent)
  }

  let containerClass = showEvent ? "absolute z-10 bg-white border-2 border-black w-64 h-64" : "hidden"

  const [evLocation, setEvLocation] = useState(eventPlace)

  function setEventLocation() {
    setEvLocation(eventPlace)
  }

  const [evDescription, setEvDescription] = useState(eventDescription)

  function setEventDescription() {
    setEvDescription(eventDescription)
  }

  const [evEffect, setEvEffect] = useState(eventEffect)

  function setEventEffect() {
    setEvEffect(eventEffect)
  }

  return (
    <>
      <Head>
        <title>Potato game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex justify-center mt-10 text-xl font-semibold">POTATO GAME</header>
      <div className="flex flex-col items-center justify-center">
        <div className="w-1/2">
          <div className="mb-5"><GameInterface destiny={destiny} potatoes={potatoes} orcs={orcs}></GameInterface></div>
          <div>You are a halfing, just trying to exist meanwhile, the dark lord rampages across the world. You do not care about this. You are trying to farm potatoes because what could a halfling possibly do about it anyway? Roll the dice and see what new day brings to you!</div>
        </div>
        <button className="border-2 border-black hover:bg-slate-400"
          onClick={() => { diceRoll(); desChange(); potChange(); orcChange(); textChange(); showEventWindow(); setEventLocation(); setEventDescription(); setEventEffect() }}>
          roll dice!
        </button>
        <div className={containerClass}>
          <div className="flex flex-col justify-center align-center">
            <div className="font-semibold text-lg text-center">{evLocation}</div>
            <div className="text-center my-5">{evDescription}</div>
            <div className="flex gap-x-5 text-center ml-5 mb-5 font-semibold">
              <div>Destiny
                <div className="font-normal">-{evEffect[0]}</div>
              </div>
              <div>Potatoes
                <div className="font-normal">-{evEffect[1]}</div>
              </div>
              <div>Orcs
                <div className="font-normal">-{evEffect[2]}</div>
              </div>
            </div>
            <button className="border-2 border-black hover:bg-slate-400" onClick={showEventWindow}>ok</button>
          </div>
        </div>
        <div>{text}</div>
      </div>
    </>
  )
}

export default Home
