import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import { diceRoll, useDestiny, usePotatoes, useOrcs, txt, eventPlace, eventDescription, eventEffect, locationDiceRoll } from '../game/game-logic'

export function GameInterface(props: { destiny: number, potatoes: number, orcs: number }) {
  return (
    <div className='border-2 border-black'>
      <div className="flex gap-5 flex-col mr-auto ml-36">
        <div className="destiny flex flex-row gap-5">
          <div className="mr-3">Destiny</div>
          <div>{props.destiny}</div>
        </div>
        <div className="potatoes flex flex-row gap-5">
          <div className="">Potatoes</div>
          <div>{props.potatoes}</div>
        </div>
        <div className="orcs flex flex-row gap-5">
          <div className="mr-8">Orcs</div>
          <div>{props.orcs}</div>
        </div>
      </div>
    </div>
  )
}

const Home: NextPage = () => {

  const { destiny, desChange } = useDestiny()
  const { potatoes, potChange } = usePotatoes()
  const { orcs, orcChange } = useOrcs()

  const [text, setText] = useState(txt)

  function textChange() {
    setText(txt)
  }

  let [showEvent, setShowEvent] = useState(false)

  function showEventWindow() {
    setShowEvent(!showEvent)
    console.log(showEvent)
  }

  let containerClass = showEvent ? "absolute z-10 bg-white border-2 border-black w-64 h-64" : "hidden"

  const [evLocation, setEvLocation] = useState(eventPlace)

  function setEventLocation() {
    setEvLocation(eventPlace)
  }

  const [evDescription, setEvDescription] = useState(eventDescription)

  function setEventDescription() {
    setEvDescription(eventDescription)
  }

  const [evEffect, setEvEffect] = useState(eventEffect)

  function setEventEffect() {
    setEvEffect(eventEffect)
  }

  const [showModalText, setShowModalText] = useState(false)

  function setModalTextClass() {
    setShowModalText(!showModalText)
  }

  let modalTextCls = showModalText ? "hidden" : ""

  let modalBtnCls = showModalText ? "border-2 border-black hover:bg-slate-400 mt-24" : "hidden"

  let modalTxtCls = showModalText ? "text-center" : "hidden"

  const [modalTxt, setModalTxt] = useState("You spend your day")

  function setPreviewText() {
    if (evLocation == "In the Garden...") {
      setModalTxt("While working in the garden you notice something...")
    }
    else if (evLocation === "A knock at the door...") {
      setModalTxt("You hear something at your door...")
    }
  }

  return (
    <>
      <Head>
        <title>Potato game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex justify-center mt-10 text-xl font-semibold">POTATO GAME</header>
      <div className="flex flex-col items-center justify-center">
        <div className="w-1/2">
          <div className="mb-5"><GameInterface destiny={destiny} potatoes={potatoes} orcs={orcs}></GameInterface></div>
          <div>You are a halfing, just trying to exist meanwhile, the dark lord rampages across the world. You do not care about this. You are trying to farm potatoes because what could a halfling possibly do about it anyway? Roll the dice and see what new day brings to you!</div>
        </div>
        <button className="border-2 border-black hover:bg-slate-400"
          onClick={() => { diceRoll(); showEventWindow(); setEventLocation(); setModalTextClass(); setPreviewText(); }}>
          roll dice!
        </button>
        
        {/* EVENT ~MODAL WINDOW */}
        <div className={containerClass}>
          <div className="flex flex-col justify-center align-center">
            <div className="font-semibold text-lg text-center">{evLocation}</div>
            <div className={modalTxtCls}>{modalTxt}</div>
            <button onClick={() => { setModalTextClass(); locationDiceRoll(); desChange(); potChange(); orcChange(); textChange(); setEventDescription(); setEventEffect(); }} 
            className={modalBtnCls}>
              Roll the dice and see what it is
              </button>
            <div className={modalTextCls}>
              <div className="text-center my-5">{evDescription}</div>
              <div className="flex gap-x-5 text-center ml-5 mb-5 font-semibold">
                <div>Destiny
                  <div className="font-normal">{evEffect[0]}</div>
                </div>
                <div>Potatoes
                  <div className="font-normal">{evEffect[1]}</div>
                </div>
                <div>Orcs
                  <div className="font-normal">{evEffect[2]}</div>
                </div>
              </div>
              <button className="border-2 border-black hover:bg-slate-400 ml-24 w-10" onClick={showEventWindow}>ok</button>
            </div>
          </div>
        </div>
        {/* END OF EVENT ~MODAL WINDOW */}

        <div className="font-semibold">Past Event</div>
        <div>{text}</div>
      </div>
    </>
  )
}

export default Home
